info:
  component: Config Server
spring:
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        test: hello
        database: mysql
        url: localhost
  datasource:
    url: jdbc:mysql://10.200.51.252:3306/platform?useUnicode=true&characterEncoding=utf-8
    username: platform
    password: platform
    driver-class-name : com.mysql.jdbc.Driver

server:
  port: 8888
management:
  context_path: /admin
 